- name: Acte 1 - essai csr1000
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
    # Configurer les adresses IP des interfaces
    

    - name: Interface GigabitEthernet2 
      cisco.ios.ios_l3_interfaces:
        config:
         - name: GigabitEthernet2
           ipv4:
            - address: 192.168.2.1/24
          

    - name: Interface GigabitEthernet3 
      cisco.ios.ios_l3_interfaces:
        config:
         - name: GigabitEthernet3
           ipv4:
            - address: 192.168.3.1/24
          

    
    - name: Interface GigabitEthernet4 
      cisco.ios.ios_l3_interfaces:
        config:
         - name: GigabitEthernet4
           ipv4:
            - address: 192.168.4.1/24
       

    - name: Activer les interfaces
      ios_config:
            lines:
             - no shutdown
            parents: 
             - interface GigabitEthernet2
             - interface GigabitEthernet3
             - interface GigabitEthernet4


    - name: Configurer le pool DHCP
      cisco.ios.ios_config:
            lines:
             - no ip dhcp pool dhcppool

    - name: Configurer le pool DHCP2
      cisco.ios.ios_config:
        parents: ["ip dhcp pool dhcppool"]
        lines:
            - network 192.168.2.0 255.255.255.0
            - default-router 192.168.2.1
            - exit
            - service dhcp
    - name: Définir les interfaces LAN comme "inside"
      cisco.ios.ios_config:
        lines:
           - ip nat inside
        parents: "interface {{ item }}"
      loop:
            - GigabitEthernet2
            - GigabitEthernet3
            - GigabitEthernet4

    - name: Définir l'interface WAN comme "outside"
      cisco.ios.ios_config:
         lines:
             - ip nat outside
         parents: "interface GigabitEthernet1"

    - name: Configurer l'ACL pour le NAT dynamique
      cisco.ios.ios_config:
        lines: "access-list 1 permit {{ item}} 0.0.0.255"
      loop:
        - 192.168.2.0
        - 192.168.3.0
        - 192.168.4.0
    - name: Activer le NAT dynamique avec surcharge
      cisco.ios.ios_config:
        lines:
          - ip nat inside source list 1 interface GigabitEthernet1 overload

    - name: Rediriger le port 80 vers le serveur web interne
      ios_config:
        lines:
          - ip nat inside source static tcp 192.168.3.2 80 interface GigabitEthernet1 80
         
        parents: "interface {{ item }}"
      loop:
        - GigabitEthernet2
        - GigabitEthernet3
        - GigabitEthernet4
    - name: Rediriger le port 2222 vers le serveur SSH interne (port 22)
      ios_config:
        lines:
          - ip nat inside source static tcp 192.168.4.2 22 interface GigabitEthernet1 2222

        parents: "interface {{ item }}"
      loop:
        - GigabitEthernet2
        - GigabitEthernet3
        - GigabitEthernet4

        

         
    